# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f6f51c9fe46e17d8acd3c732b4e4ad4c94f0e9a7ceaf3d84321f72362cd97ec44057ee53db3b1fb9acb900769985bc83eabb7395c349e2441e278026a83e81d

test:
  secret_key_base: 1cb303f2fad04e9127e5ea7f253e78f0717a48f4f3e1054063851b7e39447260d1c3a19cf3b0438c6e3773b43a551fcb0befe1de9bcd9ad845a688cf0c5a2f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
